export const ALL_PRODUCT_REQUEST ="ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS ="ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL ="ALL_PRODUCT_REQUEST";
export const CLEAR_ERROR ="CLEAR_ERROR";
export const PRODUCT_DETAILS_REQUEST ="ALL_PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS ="ALL_PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL ="ALL_PRODUCT_DETAILS_REQUEST";

